name: BusinessCardScanner
options:
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

targets:
  BusinessCardScanner:
    type: application
    platform: iOS
    sources:
      - path: .
        excludes:
          - project.yml
          - "*.xcodeproj"
          - "*.xcworkspace"
          - "*.xcconfig"
          - "*.xcconfig.example"
    preBuildScripts:
      - name: Check Secrets.xcconfig
        script: |
          if [ ! -f "${PROJECT_DIR}/Secrets.xcconfig" ]; then
            echo "error: Secrets.xcconfig not found. Copy Secrets.xcconfig.example to Secrets.xcconfig and fill in OLLAMA_BASE_URL, DEVELOPMENT_TEAM, and PRODUCT_BUNDLE_IDENTIFIER."
            exit 1
          fi
        basedOnDependencyAnalysis: false
    configFiles:
      Debug: Secrets.xcconfig
      Release: Secrets.xcconfig
    settings:
      base:
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: $(PRODUCT_BUNDLE_IDENTIFIER)
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        DEVELOPMENT_TEAM: $(DEVELOPMENT_TEAM)
        CODE_SIGN_STYLE: Automatic
